version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ventas
      MYSQL_USER: fer
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
